const STORAGE_KEY = 'lifeos_language';

export const LANGUAGES = {
    en: { name: 'English', dir: 'ltr', labels: { dashboard: 'Dashboard', calendar: 'Calendar', tasks: 'Tasks', shopping: 'Shopping', money: 'Money', home: 'Home', family: 'Family', goals: 'Goals', notes: 'Notes', social: 'Social Hub', ai: 'AI Assistant', currency: 'Currency', accent: 'Accent Color', darkMode: 'Dark Mode', lightMode: 'Light Mode', search: 'Search LifeOS across tasks, events, notes, goals...', welcomeKicker: 'Your personal life operating system', welcomeTitle: 'Bring your days into focus.', welcomeCopy: 'Organize tasks, money, goals, notes, family, and the moments that matter in one calm workspace.', create: 'Create an Account', signIn: 'Sign In', welcome: 'Welcome to LifeOS', name: 'Full name', email: 'Email address', password: 'Password', address: 'Address', country: 'Country', phone: 'Telephone number', close: 'Close', save: 'Save', createAccount: 'Create Account' } },
        en: { name: 'English', dir: 'ltr', labels: { language: 'Language', dashboard: 'Dashboard', calendar: 'Calendar', tasks: 'Tasks', shopping: 'Shopping', money: 'Money', home: 'Home', family: 'Family', goals: 'Goals', notes: 'Notes', social: 'Social Hub', ai: 'AI Assistant', currency: 'Currency', accent: 'Accent Color', darkMode: 'Dark Mode', lightMode: 'Light Mode', search: 'Search LifeOS across tasks, events, notes, goals...', welcomeKicker: 'Your personal life operating system', welcomeTitle: 'Bring your days into focus.', welcomeCopy: 'Organize tasks, money, goals, notes, family, and the moments that matter in one calm workspace.', create: 'Create an Account', signIn: 'Sign In', welcome: 'Welcome to LifeOS', name: 'Full name', email: 'Email address', password: 'Password', address: 'Address', country: 'Country', phone: 'Telephone number', close: 'Close', save: 'Save', createAccount: 'Create Account' } },
    ar: { name: 'العربية', dir: 'rtl', labels: { dashboard: 'لوحة التحكم', calendar: 'التقويم', tasks: 'المهام', shopping: 'التسوق', money: 'المال', home: 'المنزل', family: 'العائلة', goals: 'الأهداف', notes: 'الملاحظات', social: 'التواصل الاجتماعي', ai: 'المساعد الذكي', currency: 'العملة', accent: 'لون التمييز', darkMode: 'الوضع الداكن', lightMode: 'الوضع الفاتح', search: 'ابحث في LifeOS عن المهام والأحداث والملاحظات والأهداف...', welcomeKicker: 'نظامك الشخصي لإدارة الحياة', welcomeTitle: 'رتّب أيامك بوضوح.', welcomeCopy: 'نظّم مهامك وأموالك وأهدافك وملاحظاتك وعائلتك في مساحة واحدة.', create: 'إنشاء حساب', signIn: 'تسجيل الدخول', welcome: 'مرحباً بك في LifeOS', name: 'الاسم الكامل', email: 'البريد الإلكتروني', password: 'كلمة المرور', address: 'العنوان', country: 'الدولة', phone: 'رقم الهاتف', close: 'إغلاق', save: 'حفظ', createAccount: 'إنشاء حساب' } },
    fr: { name: 'Français', dir: 'ltr', labels: { dashboard: 'Tableau de bord', calendar: 'Calendrier', tasks: 'Tâches', shopping: 'Achats', money: 'Finances', home: 'Maison', family: 'Famille', goals: 'Objectifs', notes: 'Notes', social: 'Réseaux sociaux', ai: 'Assistant IA', currency: 'Devise', accent: 'Couleur d’accent', darkMode: 'Mode sombre', lightMode: 'Mode clair', search: 'Rechercher dans LifeOS...', welcomeKicker: 'Votre système personnel de vie', welcomeTitle: 'Donnez du sens à vos journées.', welcomeCopy: 'Organisez vos tâches, finances, objectifs, notes et famille au même endroit.', create: 'Créer un compte', signIn: 'Se connecter', welcome: 'Bienvenue sur LifeOS', name: 'Nom complet', email: 'Adresse e-mail', password: 'Mot de passe', address: 'Adresse', country: 'Pays', phone: 'Téléphone', close: 'Fermer', save: 'Enregistrer', createAccount: 'Créer un compte' } },
    es: { name: 'Español', dir: 'ltr', labels: { dashboard: 'Panel', calendar: 'Calendario', tasks: 'Tareas', shopping: 'Compras', money: 'Finanzas', home: 'Hogar', family: 'Familia', goals: 'Objetivos', notes: 'Notas', social: 'Redes sociales', ai: 'Asistente IA', currency: 'Moneda', accent: 'Color de acento', darkMode: 'Modo oscuro', lightMode: 'Modo claro', search: 'Buscar en LifeOS...', welcomeKicker: 'Tu sistema personal de vida', welcomeTitle: 'Enfoca tus días.', welcomeCopy: 'Organiza tus tareas, finanzas, objetivos, notas y familia en un solo lugar.', create: 'Crear cuenta', signIn: 'Iniciar sesión', welcome: 'Bienvenido a LifeOS', name: 'Nombre completo', email: 'Correo electrónico', password: 'Contraseña', address: 'Dirección', country: 'País', phone: 'Teléfono', close: 'Cerrar', save: 'Guardar', createAccount: 'Crear cuenta' } },
    de: { name: 'Deutsch', dir: 'ltr', labels: { dashboard: 'Übersicht', calendar: 'Kalender', tasks: 'Aufgaben', shopping: 'Einkaufen', money: 'Finanzen', home: 'Haushalt', family: 'Familie', goals: 'Ziele', notes: 'Notizen', social: 'Soziale Medien', ai: 'KI-Assistent', currency: 'Währung', accent: 'Akzentfarbe', darkMode: 'Dunkelmodus', lightMode: 'Hellmodus', search: 'LifeOS durchsuchen...', welcomeKicker: 'Dein persönliches Lebenssystem', welcomeTitle: 'Bringe deine Tage in den Fokus.', welcomeCopy: 'Organisiere Aufgaben, Finanzen, Ziele, Notizen und Familie an einem Ort.', create: 'Konto erstellen', signIn: 'Anmelden', welcome: 'Willkommen bei LifeOS', name: 'Vollständiger Name', email: 'E-Mail-Adresse', password: 'Passwort', address: 'Adresse', country: 'Land', phone: 'Telefonnummer', close: 'Schließen', save: 'Speichern', createAccount: 'Konto erstellen' } },
    nl: { name: 'Nederlands', dir: 'ltr', labels: { dashboard: 'Dashboard', calendar: 'Agenda', tasks: 'Taken', shopping: 'Boodschappen', money: 'Financiën', home: 'Huis', family: 'Familie', goals: 'Doelen', notes: 'Notities', social: 'Sociale media', ai: 'AI-assistent', currency: 'Valuta', accent: 'Accentkleur', darkMode: 'Donkere modus', lightMode: 'Lichte modus', search: 'Zoek in LifeOS...', welcomeKicker: 'Jouw persoonlijke levenssysteem', welcomeTitle: 'Breng je dagen in focus.', welcomeCopy: 'Organiseer taken, geld, doelen, notities en familie op één plek.', create: 'Account maken', signIn: 'Inloggen', welcome: 'Welkom bij LifeOS', name: 'Volledige naam', email: 'E-mailadres', password: 'Wachtwoord', address: 'Adres', country: 'Land', phone: 'Telefoonnummer', close: 'Sluiten', save: 'Opslaan', createAccount: 'Account maken' } },
    zh: { name: '中文', dir: 'ltr', labels: { dashboard: '仪表盘', calendar: '日历', tasks: '任务', shopping: '购物', money: '财务', home: '家庭', family: '家人', goals: '目标', notes: '笔记', social: '社交中心', ai: 'AI 助手', currency: '货币', accent: '主题颜色', darkMode: '深色模式', lightMode: '浅色模式', search: '搜索 LifeOS...', welcomeKicker: '你的个人生活操作系统', welcomeTitle: '让每一天更专注。', welcomeCopy: '在一个空间管理任务、财务、目标、笔记和家人。', create: '创建账户', signIn: '登录', welcome: '欢迎使用 LifeOS', name: '姓名', email: '电子邮箱', password: '密码', address: '地址', country: '国家', phone: '电话号码', close: '关闭', save: '保存', createAccount: '创建账户' } },
    ja: { name: '日本語', dir: 'ltr', labels: { dashboard: 'ダッシュボード', calendar: 'カレンダー', tasks: 'タスク', shopping: '買い物', money: '家計', home: 'ホーム', family: '家族', goals: '目標', notes: 'メモ', social: 'ソーシャル', ai: 'AIアシスタント', currency: '通貨', accent: 'アクセントカラー', darkMode: 'ダークモード', lightMode: 'ライトモード', search: 'LifeOSを検索...', welcomeKicker: 'あなたの生活オペレーティングシステム', welcomeTitle: '毎日に集中しましょう。', welcomeCopy: 'タスク、家計、目標、メモ、家族を一つの場所で管理できます。', create: 'アカウント作成', signIn: 'ログイン', welcome: 'LifeOSへようこそ', name: '氏名', email: 'メールアドレス', password: 'パスワード', address: '住所', country: '国', phone: '電話番号', close: '閉じる', save: '保存', createAccount: 'アカウント作成' } },
};

export function getLanguage() { return localStorage.getItem(STORAGE_KEY) || 'en'; }
export function t(key) { return LANGUAGES[getLanguage()]?.labels[key] || LANGUAGES.en.labels[key] || key; }
export function applyLanguage(language) {
    const key = LANGUAGES[language] ? language : 'en';
    localStorage.setItem(STORAGE_KEY, key);
    document.documentElement.lang = key;
    document.documentElement.dir = LANGUAGES[key].dir;
    document.documentElement.dataset.language = key;
    document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = t(element.dataset.i18nPlaceholder); });
    return key;
}
export function initLanguageSelector() {
    const select = document.getElementById('language-select');
    if (!select) return;
    select.innerHTML = Object.entries(LANGUAGES).map(([key, language]) => `<option value="${key}">${language.name}</option>`).join('');
    select.value = getLanguage();
    select.onchange = () => { applyLanguage(select.value); window.location.reload(); };
    applyLanguage(select.value);
}
